# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               thinkGeist
tagline:             'A Development Blog'
description:         'Placeholder description'
url:                 http://blog.thinkgeist.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nathan Geist
  url:               https://thinkgeist.com
  email:             nathan@thinkgeist.com

# Custom vars
version:             1.0.0
